security:
  oauth2:
    client:
      clientId: pluralsight
      clientSecret: pluralsight
      accessTokenUri: http://localhost:9000/login/oauth/access_token
      userAuthorizationUri: http://localhost:9000/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:9000/user
      preferTokenInfo: false
